GET http://localhost:3001/users
Access-Control-Allow-Origin: http://localhost:3001/users

###

POST http://localhost:3001/users
Content-Type: application/json

{
  "title": "satya",
  "body": "hello"
}